sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: BgGCz4dzmcZRfziqcj682vol574g3sMScFzvYOTglyZ+9/v2dpdiYOviczYtKNzKXeGbC1g25I3cPszJfSkOPSByAjWx0JxDyZb4lbcHfWoD62Oit+88U3HxGJ1c4p1cw05UzlGjwIvHT3oRMrZTKzCwnocdf+zJz6Pedj16/qa1HiG33UdD6tj2nslVmYAWBSRmkLyNRKUGrfl9XWmwOeVsbFs9rlOCkbMhNynvTrRkALKpCp2PPb+1sAQ0qpkdaUTNLuk0VcatcKRZfGjvyxrEATnzCCVfIEHNo2z487HacrMcCm6bvccOamJ7Gla+/+uSjMF9s8wKHvWvKAcuxTkvjVX2Fc2Rk5ZMTCdSOhpEzZzFpXn9a30C5GozGGTKUddQUIyYlbEdlhWJD9T5pikGSgd3Flzy8Eq2kqMyVYUSjxGqnnIjpm5lhcaaDQCMhX1fCUlYKG20Bs0QJLdaFHxTulnZuqtn4b2pS90jkKkjd3/WeGXmfzcUzZgV/r5/M4EAb57XBQwIuyXlU8S2NSqrargGKEzurnYCbP/dLS7SbEjzKx/mgft53+JSsiOR7oFcRE7XB90Oxqh2C5tVTCktyfe0N8WbdJTaT1T5BEf7W490hPrPjR5yqdqQG6alQ+cmLI0aHfC/6FaY//DluSQ1nwV/hgQtaj5B2k0yeYU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Twilight-Stories_594
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy